[package]
name = "phala-blockchain-node"
version = "2.0.0-dev"
authors = ["Jasl"]
description = "Phala Substrate Node"
edition = "2018"
license = "Unlicense"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "phala-node"
path = "bin/main.rs"
required-features = ["cli"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"

sc-cli = { version = "0.8.0-dev", path = "../substrate/client/cli" }
sp-core = { version = "2.0.0-dev", path = "../substrate/primitives/core" }
sc-executor = { version = "0.8.0-dev", path = "../substrate/client/executor" }
sc-service = { version = "0.8.0-dev", path = "../substrate/client/service" }
sp-inherents = { version = "2.0.0-dev", path = "../substrate/primitives/inherents" }
sc-transaction-pool = { version = "2.0.0-dev", path = "../substrate/client/transaction-pool" }
sp-transaction-pool = { version = "2.0.0-dev", path = "../substrate/primitives/transaction-pool" }
sc-network = { version = "0.8.0-dev", path = "../substrate/client/network" }
sc-consensus-babe = { version = "0.8.0-dev", path = "../substrate/client/consensus/babe" }
sp-consensus-babe = { version = "0.8.0-dev", path = "../substrate/primitives/consensus/babe" }
sp-consensus = { version = "0.8.0-dev", path = "../substrate/primitives/consensus/common" }
sc-consensus = { version = "0.8.0-dev", path = "../substrate/client/consensus/common" }
sc-finality-grandpa = { version = "0.8.0-dev", path = "../substrate/client/finality-grandpa" }
sp-finality-grandpa = { version = "2.0.0-dev", path = "../substrate/primitives/finality-grandpa" }
sc-client-api = { version = "2.0.0-dev", path = "../substrate/client/api" }
sp-runtime = { version = "2.0.0-dev", path = "../substrate/primitives/runtime" }
sc-basic-authorship = { path = "../substrate/client/basic-authorship", version = "0.8.0-dev"}

node-runtime = { version = "2.0.0-dev", path = "../runtime", package = "phala-blockchain-runtime" }
node-rpc = { version = "2.0.0-dev", path = "../substrate/bin/node/rpc" }
node-primitives = { version = "2.0.0-dev", path = "../substrate/bin/node/primitives" }
node-executor = { version = "2.0.0-dev", path = "../substrate/bin/node/executor" }

codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
base64 = "*"
# sp-state-machine = { version = "2.0.0-dev", path = "../substrate/primitives/state-machine" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0-dev", path = "../substrate/utils/build-script-utils" }
